"""add visibility_rules

Revision ID: 27a173f304a5
Revises: 8b8c2cadcafc
Create Date: 2026-06-28 17:29:33.991407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a173f304a5'
down_revision: Union[str, Sequence[str], None] = '8b8c2cadcafc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visibility_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_question_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_assessment_question_id', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('expected_value_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_question_id'], ['assessment_questions.id'], ),
    sa.ForeignKeyConstraint(['depends_on_assessment_question_id'], ['assessment_questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_question_id')
    )
    op.create_index(op.f('ix_visibility_rules_id'), 'visibility_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visibility_rules_id'), table_name='visibility_rules')
    op.drop_table('visibility_rules')
    # ### end Alembic commands ###
